# Generated by Django 4.2.1 on 2023-06-13 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_title', models.CharField(max_length=255)),
                ('created_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_relation', to='backend.table')),
                ('relation_table', models.ManyToManyField(related_name='relation_connected_to', to='backend.table')),
            ],
        ),
    ]
