# Generated by Django 4.2.1 on 2023-07-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_company_address_line_alter_company_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='firstname',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.TextField(),
        ),
    ]
