# Generated by Django 4.2.1 on 2023-07-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_company_company_name_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='lastname',
            field=models.TextField(blank=True, null=True),
        ),
    ]
